In [2]:
import numpy as np
from numpy.linalg import svd

In [16]:
A = np.array([[0, 2, 0], [-3, 0, 0], [0, 0, 1]])
A

array([[ 0,  2,  0],
       [-3,  0,  0],
       [ 0,  0,  1]])

In [27]:
u, s, vh = svd(A)
A_1 = s @ u @ v.T

In [33]:
s1 = s[0]
u1 = u[:, 0]
v1 = vh[0, :]
u2 = u[:, 1]
v2 = vh[1, :]
A2 = s[0] * np.outer(u1, v1) + s[1] * np.outer(u2, v2)
A2

array([[ 0.,  2.,  0.],
       [-3.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [35]:
s[2]

np.float64(1.0)

In [29]:
s[1]

np.float64(2.0)

In [36]:
np.linalg.norm(A - A2, 2)

np.float64(1.0)

In [23]:
u[0] @ v[0].T

np.float64(0.0)

In [14]:
np.linalg.eig(A @ A.T)[0]

array([ 6.48334192e+02,  1.66580756e+00,  4.62653469e-15, -1.61209025e-14])

In [13]:
for i in np.linalg.eig(A @ A.T)[0]:
    print(np.sqrt(i))

25.462407436036393
1.2906616757612295
6.801863490668582e-08
nan


/var/folders/kr/wftdhl5d7p737kpxp30dm9w00000gp/T/ipykernel_11101/580383820.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(i))


In [9]:
svd(A)

SVDResult(U=array([[ 0.16018224,  0.98708746],
       [ 0.98708746, -0.16018224]]), S=array([3.3409995 , 2.19948229]), Vh=array([[ 0.93428467,  0.19955794,  0.29544675],
       [ 0.23029998, -0.9703907 , -0.07282725],
       [-0.27216553, -0.13608276,  0.95257934]]))

In [15]:
import numpy as np

def rref(A, tol=1e-10):
    A = A.astype(float)  # work with floats
    rows, cols = A.shape
    r = 0  # row index for pivot

    for c in range(cols):
        # Find the pivot row
        pivot = np.argmax(np.abs(A[r:rows, c])) + r
        if np.abs(A[pivot, c]) < tol:
            continue  # no pivot in this column, move to next column
        # Swap current row and pivot row
        A[[r, pivot]] = A[[pivot, r]]
        # Normalize pivot row
        A[r] = A[r] / A[r, c]
        # Eliminate entries in the current column
        for i in range(rows):
            if i != r:
                A[i] = A[i] - A[i, c] * A[r]
        r += 1
        if r == rows:
            break
    return A

A_rref = rref(A)
print("RREF of A:")
print(A_rref)


RREF of A:
[[ 1.00000000e+00  0.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.66533454e-15]
 [ 0.00000000e+00  0.00000000e+00  6.66133815e-16]]
