In [2]:
import numpy as np

In [26]:
A = np.array([[3,-3], [9,-10], [-21, 23]])
A

array([[  3,  -3],
       [  9, -10],
       [-21,  23]])

In [27]:
P = A @ np.linalg.inv(A.T@A)@A.T

In [28]:
P

array([[ 0.83333333, -0.33333333, -0.16666667],
       [-0.33333333,  0.33333333, -0.33333333],
       [-0.16666667, -0.33333333,  0.83333333]])

In [29]:
b = np.array([-11, -36, 80])

for row in P:
    print(abs(row-b))

[11.83333333 35.66666667 80.16666667]
[10.66666667 36.33333333 80.33333333]
[10.83333333 35.66666667 79.16666667]


In [30]:
P @ b

array([-10.5, -35. ,  80.5])

In [18]:
np.identity(2) - P

array([[ 0.125  , -0.40625],
       [-0.0625 ,  0.46875]])